export const bonuses = [
  {
    id: "hook-vault",
    title: "Mega E-Commerce Hook Vault",
    desc: "مكتبة ضخمة من أنماط الـ Hooks الأكثر نجاحاً في إعلانات التجارة الإلكترونية — مصنّفة حسب النوع والهدف.",
    value: "[VALUE]",
    icon: "📚",
  },
  {
    id: "angle-swipe",
    title: "Creative Angle Swipe File",
    desc: "ملف مرجعي كامل لزوايا إعلانية ثبت نجاحها في مختلف الصناعات — جاهز للتكييف مع منتجك.",
    value: "[VALUE]",
    icon: "🗂️",
  },
  {
    id: "testing-checklist",
    title: "Meta Creative Testing Checklist",
    desc: "قائمة مراجعة شاملة لكل ما تحتاج التحقق منه قبل وأثناء وبعد كل اختبار إعلاني.",
    value: "[VALUE]",
    icon: "✅",
  },
  {
    id: "winner-playbook",
    title: "Winner Expansion Playbook",
    desc: "دليل عملي خطوة بخطوة لتوسيع الـ Creatives الفائزة وزيادة العائد منها.",
    value: "[VALUE]",
    icon: "📖",
  },
  {
    id: "analysis-sheet",
    title: "Creative Performance Analysis Sheet",
    desc: "قالب تحليل أداء جاهز لتتبع وتقييم كل Creative تختبره — بأرقام واضحة.",
    value: "[VALUE]",
    icon: "📋",
  },
  {
    id: "testing-plan",
    title: "30-Day Creative Testing Plan",
    desc: "خطة اختبار كاملة لمدة 30 يوم — تعرف بالضبط ماذا تختبر كل أسبوع ولماذا.",
    value: "[VALUE]",
    icon: "📅",
  },
  {
    id: "prompt-vault",
    title: "AI Creative Prompt Vault",
    desc: "مجموعة Prompts متقدمة ومنظمة لاستخدام الـ AI في إنشاء Creatives احترافية.",
    value: "[VALUE]",
    icon: "🤖",
  },
];
