export const modules = [
  {
    id: "customer-intelligence",
    number: "01",
    title: "Customer Intelligence",
    subtitle: "افهم عميلك قبل ما تكتب كلمة",
    desc: "أدخل منتجك، واحصل على تحليل كامل لمشاكل العميل، رغباته، اعتراضاته، ومستوى وعيه — كل شيء تحتاجه قبل ما تبدأ أي Creative.",
    icon: "🧠",
  },
  {
    id: "angle-generator",
    number: "02",
    title: "Angle Generator",
    subtitle: "زوايا إعلانية مبنية على بيانات حقيقية",
    desc: "النظام يولّد زوايا إعلانية متعددة مبنية على مشاكل ورغبات واعتراضات العميل — مش مجرد أفكار عشوائية.",
    icon: "🎯",
  },
  {
    id: "hook-generator",
    number: "03",
    title: "Hook Generator",
    subtitle: "Hooks تخطف الانتباه في أول 3 ثواني",
    desc: "كل Hook مبني على Angle محدد وعلى نمط ثبت نجاحه. مش كلام عام — هذا استهداف.",
    icon: "🪝",
  },
  {
    id: "creative-concept-builder",
    number: "04",
    title: "Creative Concept Builder",
    subtitle: "من Hook إلى مفهوم Creative كامل",
    desc: "حوّل كل Hook إلى مفهوم Creative واضح: البنية، الرسالة، النبرة، والـ Call to Action.",
    icon: "🏗️",
  },
  {
    id: "script-builder",
    number: "05",
    title: "Script Builder",
    subtitle: "سكريبتات جاهزة للتصوير أو التصميم",
    desc: "احصل على سكريبتات فيديو وتصميم جاهزة — مكتوبة بناءً على الـ Concept والـ Hook والـ Angle.",
    icon: "📝",
  },
  {
    id: "variation-engine",
    number: "06",
    title: "Creative Variation Engine",
    subtitle: "نسخ متعددة لاختبارها ضد بعضها",
    desc: "أنشئ variations من نفس الـ Creative: غيّر الـ Hook، النبرة، الطول، أو البنية — وجهّز اختبارات A/B حقيقية.",
    icon: "🔀",
  },
  {
    id: "testing-framework",
    number: "07",
    title: "Testing Framework",
    subtitle: "اعرف بالضبط ماذا تختبر ولماذا",
    desc: "إطار اختبار منظم: ماذا تختبر، ماذا تتوقع، كيف تقيس النتائج، وكيف تأخذ قرار.",
    icon: "🧪",
  },
  {
    id: "creative-analysis",
    number: "08",
    title: "Creative Analysis",
    subtitle: "حلل النتائج وافهم لماذا نجح أو فشل",
    desc: "أدخل نتائج الاختبار، والنظام يحلل: لماذا نجح هذا Creative؟ لماذا فشل الآخر؟ ماذا تتعلم؟",
    icon: "📊",
  },
  {
    id: "winner-expansion",
    number: "09",
    title: "Winner Expansion",
    subtitle: "الفائز ليس النهاية — الفائز هو البداية",
    desc: "خذ الـ Creative الفائز ووسّعه: hooks جديدة، angles جديدة، audiences جديدة — بناءً على ما تعلمته.",
    icon: "🚀",
  },
  {
    id: "next-test-generator",
    number: "10",
    title: "Next-Test Generator",
    subtitle: "ماذا تختبر بعد ذلك؟",
    desc: "بناءً على كل النتائج والتعلمات، النظام يقترح الاختبار القادم: ماذا تغير، ماذا تثبت، وماذا تجرب.",
    icon: "🔄",
  },
];
