export const pricing = {
  badge: "عرض الإطلاق",
  headline: "احصل على النظام الكامل",
  price: "[PRICE]",
  originalPrice: "[ORIGINAL_PRICE]",
  currency: "دج",
  paymentMethods: "BaridiMob · CCP · Chargily",
  cta: "احصل على النظام الآن",
  note: "وصول فوري بعد الدفع",
};

export const valueStack = [
  { item: "النظام الأساسي — AI Creative & Ad Testing System", value: "[VALUE]" },
  { item: "Customer Intelligence Module", value: "[VALUE]" },
  { item: "Angle Generator Engine", value: "[VALUE]" },
  { item: "Hook Generator Engine", value: "[VALUE]" },
  { item: "Creative Concept Builder", value: "[VALUE]" },
  { item: "Script Builder", value: "[VALUE]" },
  { item: "Creative Variation Engine", value: "[VALUE]" },
  { item: "Testing Framework", value: "[VALUE]" },
  { item: "Creative Analysis Module", value: "[VALUE]" },
  { item: "Winner Expansion System", value: "[VALUE]" },
  { item: "Next-Test Generator", value: "[VALUE]" },
  { item: "Mega E-Commerce Hook Vault", value: "[VALUE]" },
  { item: "Creative Angle Swipe File", value: "[VALUE]" },
  { item: "Meta Creative Testing Checklist", value: "[VALUE]" },
  { item: "Winner Expansion Playbook", value: "[VALUE]" },
  { item: "Creative Performance Analysis Sheet", value: "[VALUE]" },
  { item: "30-Day Creative Testing Plan", value: "[VALUE]" },
  { item: "AI Creative Prompt Vault", value: "[VALUE]" },
];
